services:
  yarp:
    image: brunomartens/yarp:latest
    ports:
      - 8080:8080
      - 4433:8081
    networks:
      - brunomartens
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ./https:/https
  api:
    image: brunomartens/api:latest
    networks:
      - brunomartens
  portal:
    image: brunomartens/portal:latest
    networks:
      - brunomartens

networks:
  brunomartens:
    driver: bridge