services:
  yarp:
    build:
      context: .
      dockerfile: ./brunomartens.yarp/Dockerfile
    ports:
      - 8080:8080
      - 4433:8081
    networks:
      - brunomartens
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ./https:/https
  api:
    build:
      context: .
      dockerfile: ./brunomartens.web/Dockerfile
    networks:
      - brunomartens
  portal:
    build:
      context: .
      dockerfile: ./brunomartens.angular/Dockerfile
    networks:
      - brunomartens

networks:
  brunomartens:
    driver: bridge